package com.app.ai;

import com.app.dto.AiGenerateDiagramRequest;
import com.app.dto.AiGenerateDocumentRequest;
import com.app.dto.AiGenerationResponse;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import org.springframework.stereotype.Service;

@Service
public class AiGenerationService {

  private final ObjectMapper objectMapper;
  private final OllamaClient ollamaClient;
  private final OllamaJsonSanitizer jsonSanitizer;
  private final OllamaProperties ollamaProperties;

  public AiGenerationService(
      ObjectMapper objectMapper,
      OllamaClient ollamaClient,
      OllamaJsonSanitizer jsonSanitizer,
      OllamaProperties ollamaProperties) {
    this.objectMapper = objectMapper;
    this.ollamaClient = ollamaClient;
    this.jsonSanitizer = jsonSanitizer;
    this.ollamaProperties = ollamaProperties;
  }

  public AiGenerationResponse generateDiagram(AiGenerateDiagramRequest request) {
    String model = modelOrDefault(request.model());
    if (ollamaProperties.enabled()) {
      try {
        JsonNode graph = generateOllamaGraph(request.prompt(), model);
        String title = titleFromPrompt(request.prompt());
        return new AiGenerationResponse(
            "OLLAMA",
            "Generated architecture graph JSON with local Ollama model.",
            model,
            title,
            graph,
            null,
            List.of("Graph generated by local Ollama. Layout remains handled by the frontend."),
            interviewQuestionsFor(request.prompt()));
      } catch (RuntimeException exception) {
        MockSystemDesign fallback = designFor(request.prompt());
        return new AiGenerationResponse(
            "MOCK_FALLBACK",
            fallbackMessage(exception, "graph JSON"),
            model,
            fallback.title(),
            graphFor(fallback),
            null,
            fallback.explanation(),
            fallback.interviewQuestions());
      }
    }

    MockSystemDesign design = designFor(request.prompt());
    return new AiGenerationResponse(
        "MOCK_AI",
        "Generated deterministic mock architecture graph JSON. Enable Ollama to use a local model.",
        model,
        design.title(),
        graphFor(design),
        null,
        design.explanation(),
        design.interviewQuestions());
  }

  public AiGenerationResponse generateDocument(AiGenerateDocumentRequest request) {
    String model = modelOrDefault(request.model());
    if (ollamaProperties.enabled()) {
      try {
        String markdown = generateOllamaDocument(request.prompt(), model);
        return new AiGenerationResponse(
            "OLLAMA",
            "Generated technical design document with local Ollama model.",
            model,
            titleFromPrompt(request.prompt()),
            null,
            markdown,
            List.of("Document generated by local Ollama."),
            interviewQuestionsFor(request.prompt()));
      } catch (RuntimeException exception) {
        MockSystemDesign fallback = designFor(request.prompt());
        return new AiGenerationResponse(
            "MOCK_FALLBACK",
            fallbackMessage(exception, "Markdown"),
            model,
            fallback.title(),
            null,
            markdownFor(fallback),
            fallback.explanation(),
            fallback.interviewQuestions());
      }
    }

    MockSystemDesign design = designFor(request.prompt());
    return new AiGenerationResponse(
        "MOCK_AI",
        "Generated deterministic mock technical design document. Enable Ollama to use a local model.",
        model,
        design.title(),
        null,
        markdownFor(design),
        design.explanation(),
        design.interviewQuestions());
  }

  private JsonNode generateOllamaGraph(String prompt, String model) {
    RuntimeException lastFailure = null;
    for (int attempt = 0; attempt < ollamaProperties.retries(); attempt++) {
      try {
        String rawResponse = ollamaClient.generate(model, diagramPrompt(prompt), true);
        JsonNode graph =
            jsonSanitizer
                .sanitizeGraph(rawResponse)
                .orElseThrow(() -> new IllegalStateException("Ollama returned malformed graph JSON"));
        List<String> problems = jsonSanitizer.structuralProblems(graph);
        if (!problems.isEmpty()) {
          throw new IllegalStateException(
              "Ollama returned an unusable graph (%s)".formatted(String.join("; ", problems)));
        }
        return graph;
      } catch (RuntimeException exception) {
        lastFailure = exception;
        if (exception instanceof OllamaUnavailableException) {
          break;
        }
      }
    }
    throw lastFailure == null ? new IllegalStateException("Ollama graph generation failed") : lastFailure;
  }

  private String generateOllamaDocument(String prompt, String model) {
    RuntimeException lastFailure = null;
    for (int attempt = 0; attempt < ollamaProperties.retries(); attempt++) {
      try {
        String markdown = ollamaClient.generate(model, documentPrompt(prompt), false).trim();
        if (markdown.startsWith("```")) {
          markdown = markdown.replaceFirst("(?s)^```(?:markdown)?\\s*", "").replaceFirst("(?s)\\s*```$", "");
        }
        if (!markdown.contains("## Overview")) {
          throw new IllegalStateException("Ollama document missed required sections");
        }
        return markdown;
      } catch (RuntimeException exception) {
        lastFailure = exception;
        if (exception instanceof OllamaUnavailableException) {
          break;
        }
      }
    }
    throw lastFailure == null ? new IllegalStateException("Ollama document generation failed") : lastFailure;
  }

  private String diagramPrompt(String prompt) {
    return """
        You generate architecture diagrams for system design interview preparation.

        Return ONLY one valid JSON object. Do not use markdown. Do not include prose.
        The JSON object must have exactly these top-level keys:
        {
          "nodes": [],
          "edges": []
        }

        Node schema:
        {
          "id": "stable-kebab-case-id",
          "type": "service|database|cache|queue|gateway|mobile|cdn|loadBalancer|kafka|redis|websocket|aws|ec2|lambda|ecs|eks|s3|rds|dynamodb|opensearch|cloudfront|apiGateway|sqs|sns|vpc",
          "data": {
            "label": "Human label",
            "description": "Short technical purpose"
          }
        }

        Edge schema:
        {
          "source": "source-node-id",
          "target": "target-node-id",
          "label": "protocol or flow"
        }

        Rules:
        - Never include x/y positions.
        - Never include SVG, Mermaid, HTML, or canvas instructions.
        - Use 6 to 10 nodes.
        - Every edge source and target must reference an existing node id.
        - Every node must appear in at least one edge. Never emit an isolated node.
        - Use at least (number of nodes - 1) edges so the whole diagram is one connected flow
          that can be traced from the client through to storage.
        - Name services after the domain in the user prompt, not generic infrastructure.
          A prompt about expense sharing should produce components such as "Expense Service",
          "Group Service", "Settlement Service" - not just "Service A" or a bare cloud stack.
        - Use the generic types (service, database, cache, queue, gateway, mobile) by default.
          Only use the AWS-specific types when the user prompt explicitly names AWS, a specific
          AWS service, or asks for a cloud-provider design.
        - When the prompt does name an AWS service, set that node's "type" to the matching value:
          Lambda -> lambda, DynamoDB -> dynamodb, S3 -> s3, RDS -> rds, SQS -> sqs, SNS -> sns,
          EC2 -> ec2, ECS -> ecs, EKS -> eks, CloudFront -> cloudfront, API Gateway -> apiGateway,
          OpenSearch -> opensearch, VPC -> vpc. Do not fall back to "service" or "database" there.

        Example of the expected shape and connectivity for "design a food delivery app":
        {
          "nodes": [
            {"id": "customer-app", "type": "mobile", "data": {"label": "Customer App", "description": "Browses restaurants and places orders"}},
            {"id": "api-gateway", "type": "gateway", "data": {"label": "API Gateway", "description": "Authenticates and routes requests"}},
            {"id": "order-service", "type": "service", "data": {"label": "Order Service", "description": "Owns order lifecycle and pricing"}},
            {"id": "restaurant-service", "type": "service", "data": {"label": "Restaurant Service", "description": "Serves menus and availability"}},
            {"id": "order-db", "type": "database", "data": {"label": "Order Store", "description": "Durable order and payment records"}},
            {"id": "menu-cache", "type": "cache", "data": {"label": "Menu Cache", "description": "Caches hot restaurant menus"}},
            {"id": "delivery-queue", "type": "queue", "data": {"label": "Dispatch Queue", "description": "Hands off orders to courier assignment"}}
          ],
          "edges": [
            {"source": "customer-app", "target": "api-gateway", "label": "HTTPS"},
            {"source": "api-gateway", "target": "order-service", "label": "place order"},
            {"source": "api-gateway", "target": "restaurant-service", "label": "browse"},
            {"source": "restaurant-service", "target": "menu-cache", "label": "hot menus"},
            {"source": "order-service", "target": "order-db", "label": "persist"},
            {"source": "order-service", "target": "delivery-queue", "label": "dispatch"}
          ]
        }

        User prompt: %s
        """
        .formatted(prompt);
  }

  private String documentPrompt(String prompt) {
    return """
        You write technical design documents for system design interview preparation.
        Return Markdown only. Do not wrap the answer in code fences.

        Include these sections exactly:
        # <System Name>
        ## Overview
        ## Requirements
        ### Functional Requirements
        ### Non Functional Requirements
        ## Capacity Estimation
        ## Core Components
        ## APIs
        ## Database Design
        ## Scaling
        ## Bottlenecks
        ## Security
        ## Tradeoffs
        ## Interview Discussion Points

        Keep the answer practical, concise, and backend-system focused.

        User prompt: %s
        """
        .formatted(prompt);
  }

  private String titleFromPrompt(String prompt) {
    String lowerPrompt = prompt.toLowerCase(Locale.ROOT);
    if (lowerPrompt.contains("url")
        && (lowerPrompt.contains("shortener") || lowerPrompt.contains("shortner"))) {
      return "URL Shortener";
    }
    String normalized =
        prompt
            .replaceFirst(
                "(?i)^\\s*(design|create|build|make|generate|document|documentation\\s+for)\\s+",
                "")
            // "design me splitwise" and "build a chat app" otherwise keep the filler
            // word and title themselves "Me Splitwise" / "A Chat App".
            .replaceFirst("(?i)^\\s*(me|us|for\\s+me|a|an|the|my|our)\\s+", "")
            .trim();
    if (normalized.isBlank()) {
      return "Generated System Design";
    }
    String[] words = normalized.split("\\s+");
    List<String> titleWords = new ArrayList<>();
    for (int index = 0; index < Math.min(words.length, 6); index++) {
      String word = words[index].replaceAll("[^A-Za-z0-9-]", "");
      if (!word.isBlank()) {
        titleWords.add(word.substring(0, 1).toUpperCase(Locale.ROOT) + word.substring(1));
      }
    }
    return titleWords.isEmpty() ? "Generated System Design" : String.join(" ", titleWords);
  }

  private List<String> interviewQuestionsFor(String prompt) {
    MockSystemDesign fallback = designFor(prompt);
    return fallback.interviewQuestions();
  }

  private MockSystemDesign designFor(String prompt) {
    String normalized = prompt.toLowerCase(Locale.ROOT);
    if (normalized.contains("url") || normalized.contains("shortener") || normalized.contains("shortner")) {
      return urlShortenerDesign();
    }
    if (normalized.contains("whatsapp") || normalized.contains("chat")) {
      return whatsappDesign();
    }
    if (normalized.contains("netflix") || normalized.contains("stream")) {
      return netflixDesign();
    }
    if (normalized.contains("youtube") || normalized.contains("recommend")) {
      return youtubeDesign();
    }
    if (normalized.contains("uber")
        || (normalized.contains("driver") && normalized.contains("tracking"))) {
      return uberDesign();
    }
    return genericDesign(prompt);
  }

  private String modelOrDefault(String model) {
    return model == null || model.isBlank() ? ollamaProperties.defaultModel() : model;
  }

  private String fallbackMessage(RuntimeException exception, String artifactType) {
    String detail =
        exception.getMessage() == null || exception.getMessage().isBlank()
            ? "Ollama was unavailable"
            : exception.getMessage();
    detail = detail.replaceFirst("[.!?]+$", "");
    return "%s. Showing deterministic mock %s instead.".formatted(detail, artifactType);
  }

  private JsonNode graphFor(MockSystemDesign design) {
    return objectMapper.valueToTree(Map.of("nodes", design.nodes(), "edges", design.edges()));
  }

  private String markdownFor(MockSystemDesign design) {
    return """
        # %s

        ## Overview

        %s

        ## Requirements

        ### Functional Requirements

        %s

        ### Non Functional Requirements

        - Low latency user-facing paths.
        - Horizontally scalable stateless services.
        - Durable event history for replay and recovery.
        - Regional isolation for high traffic spikes.

        ## Capacity Estimation

        | Metric | Mock Estimate |
        | --- | ---: |
        | Peak requests | 250k/sec |
        | Hot data TTL | 5-30 min |
        | Availability target | 99.95%% |

        ## Core Components

        %s

        ## APIs

        ```http
        POST /v1/events
        GET /v1/resources/{id}
        WS /v1/realtime/{channel}
        ```

        ## Database Design

        Use the operational database for durable state, cache hot read paths, and stream events into analytics/storage consumers.

        ## Scaling

        %s

        ## Bottlenecks

        %s

        ## Security

        Authenticate every client, rate limit public entry points, encrypt sensitive data, and scope service-to-service access by least privilege.

        ## Tradeoffs

        %s

        ## Interview Discussion Points

        %s
        """
        .formatted(
            design.title(),
            design.overview(),
            bulletList(design.functionalRequirements()),
            bulletList(design.components()),
            design.scaling(),
            bulletList(design.bottlenecks()),
            design.tradeoffs(),
            bulletList(design.interviewQuestions()));
  }

  private String bulletList(List<String> values) {
    return values.stream().map(value -> "- " + value).reduce("", (left, right) -> left + right + "\n");
  }

  private MockSystemDesign uberDesign() {
    return new MockSystemDesign(
        "Uber Realtime Driver Tracking",
        "Realtime driver location tracking uses WebSockets for rider updates, Kafka for durable location streams, Redis GEO for nearby lookup, and Cassandra for high-volume history.",
        List.of(
            node("mobile-client", "mobile", "Rider App", "Receives active trip and nearby driver updates."),
            node("driver-app", "mobile", "Driver App", "Publishes location pings every few seconds."),
            node("api-gateway", "gateway", "API Gateway", "Authenticates and rate limits mobile traffic."),
            node("ws-gateway", "websocket", "WebSocket Gateway", "Maintains realtime rider subscriptions."),
            node("tracking-service", "service", "Tracking Service", "Validates and normalizes driver location events."),
            node("kafka", "kafka", "Kafka Location Stream", "Buffers and fans out location events."),
            node("redis-geo", "redis", "Redis GEO", "Caches active driver positions for nearby search."),
            node("cassandra", "database", "Cassandra", "Stores location history by driver and time bucket.")),
        List.of(
            edge("driver-app", "api-gateway", "HTTPS"),
            edge("mobile-client", "ws-gateway", "subscribe"),
            edge("api-gateway", "tracking-service", "REST"),
            edge("tracking-service", "kafka", "publish"),
            edge("kafka", "redis-geo", "hot index"),
            edge("kafka", "cassandra", "append"),
            edge("redis-geo", "ws-gateway", "location delta")),
        List.of(
            "Drivers publish location updates.",
            "Riders subscribe to active trip updates.",
            "Dispatch queries nearby available drivers."),
        List.of(
            "API Gateway protects mobile ingress.",
            "Kafka decouples ingestion from consumers.",
            "Redis GEO keeps proximity lookup fast.",
            "Cassandra handles write-heavy historical storage."),
        "Partition streams by city/geohash, keep WebSocket gateways regional, and isolate hot Redis shards around dense zones.",
        List.of("Airport hotspots", "mobile retry storms", "out-of-order pings", "fanout pressure"),
        "WebSockets reduce polling overhead, while Kafka adds complexity in exchange for replay and backpressure.",
        List.of(
            "Why WebSockets instead of polling?",
            "How would you partition location events?",
            "What happens if Redis GEO is unavailable?",
            "How do you handle duplicate pings?"),
        List.of(
            "Kafka gives replayable location history and absorbs bursty mobile traffic.",
            "Redis GEO is used only for hot proximity lookup, not durable truth.",
            "Cassandra fits append-heavy location history."));
  }

  private MockSystemDesign urlShortenerDesign() {
    return new MockSystemDesign(
        "URL Shortener",
        "A URL shortener creates compact aliases for long URLs, redirects readers with very low latency, tracks click events asynchronously, and protects public creation endpoints from abuse.",
        List.of(
            node("web-client", "mobile", "Web/Mobile Client", "Creates short links and follows redirects."),
            node("api-gateway", "gateway", "API Gateway", "Terminates TLS, authenticates creators, and applies rate limits."),
            node("short-link-service", "service", "Short Link Service", "Validates long URLs and creates unique short codes."),
            node("redirect-service", "service", "Redirect Service", "Resolves short codes and returns HTTP 301/302 redirects."),
            node("id-generator", "service", "ID Generator", "Allocates collision-resistant Base62 codes."),
            node("link-db", "database", "Link Store", "Stores code-to-long-URL mappings and metadata."),
            node("redis-cache", "redis", "Redirect Cache", "Caches hot short-code lookups."),
            node("click-stream", "kafka", "Click Event Stream", "Captures redirect analytics without blocking users."),
            node("analytics-service", "service", "Analytics Service", "Aggregates click metrics and abuse signals.")),
        List.of(
            edge("web-client", "api-gateway", "HTTPS"),
            edge("api-gateway", "short-link-service", "create"),
            edge("short-link-service", "id-generator", "allocate code"),
            edge("short-link-service", "link-db", "persist mapping"),
            edge("web-client", "redirect-service", "GET /{code}"),
            edge("redirect-service", "redis-cache", "cache lookup"),
            edge("redirect-service", "link-db", "cache miss"),
            edge("redirect-service", "click-stream", "async click"),
            edge("click-stream", "analytics-service", "aggregate")),
        List.of(
            "Create short links for valid long URLs.",
            "Redirect short-code requests to the original URL.",
            "Support custom aliases and expiration policies.",
            "Track click analytics asynchronously."),
        List.of(
            "Short Link Service owns validation and code creation.",
            "Redirect Service is optimized for hot read latency.",
            "Redis caches popular code mappings.",
            "Kafka decouples analytics from the redirect path.",
            "Link Store remains the durable source of truth."),
        "Shard link mappings by short-code hash, keep redirect services stateless, cache hot codes at Redis/CDN edge, and process click analytics asynchronously.",
        List.of("hot celebrity links", "short-code collisions", "cache stampedes", "abusive link creation", "database read pressure"),
        "Random Base62 codes are simple and hard to enumerate, while sequential ids are compact but need extra protection against guessing.",
        List.of(
            "How do you avoid short-code collisions?",
            "When should redirects use 301 versus 302?",
            "How do you protect against malicious URLs?",
            "What is the cache invalidation strategy for expired links?"),
        List.of(
            "Redirect lookup is the critical low-latency path.",
            "Analytics should never block redirects.",
            "Rate limits and abuse checks protect public link creation."));
  }

  private MockSystemDesign genericDesign(String prompt) {
    String title = titleFromPrompt(prompt);
    String systemName = title.toLowerCase(Locale.ROOT);
    String article = systemName.matches("^[aeiou].*") ? "An" : "A";
    return new MockSystemDesign(
        title,
        "%s %s needs a clean ingress layer, focused domain services, durable storage, fast read paths, asynchronous background processing, and operational visibility."
            .formatted(article, systemName),
        List.of(
            node("client-app", "mobile", "Client App", "Users interact with the %s through web or mobile screens.".formatted(systemName)),
            node("api-gateway", "gateway", "API Gateway", "Authenticates users, applies rate limits, and routes requests."),
            node("core-service", "service", "%s Service".formatted(title), "Owns the core workflows and business rules."),
            node("worker-service", "service", "Background Worker", "Runs async jobs, notifications, imports, and scheduled tasks."),
            node("primary-db", "database", "Primary Database", "Stores durable application records and transactional state."),
            node("cache", "redis", "Read Cache", "Caches hot objects, sessions, and computed views."),
            node("event-queue", "queue", "Event Queue", "Decouples write paths from background processing."),
            node("object-storage", "database", "Object Storage", "Stores files, exports, media, and large artifacts."),
            node("observability", "service", "Observability", "Collects logs, metrics, traces, and audit events.")),
        List.of(
            edge("client-app", "api-gateway", "HTTPS"),
            edge("api-gateway", "core-service", "REST"),
            edge("core-service", "primary-db", "read/write"),
            edge("core-service", "cache", "hot reads"),
            edge("core-service", "event-queue", "publish events"),
            edge("event-queue", "worker-service", "consume jobs"),
            edge("worker-service", "object-storage", "store artifacts"),
            edge("core-service", "observability", "telemetry"),
            edge("worker-service", "observability", "job metrics")),
        List.of(
            "Create, update, search, and manage %s records.".formatted(systemName),
            "Support authenticated user workflows and role-aware access.",
            "Run asynchronous jobs without blocking user requests.",
            "Expose audit trails and operational dashboards."),
        List.of(
            "API Gateway protects public ingress.",
            "%s Service owns domain workflows.".formatted(title),
            "Primary Database is the durable source of truth.",
            "Read Cache accelerates high-frequency lookups.",
            "Event Queue keeps background work isolated from request latency."),
        "Scale stateless services horizontally, shard or partition data around the dominant access key, cache hot views, and move slow workflows to queue-backed workers.",
        List.of("hot search queries", "large exports", "background job backlog", "database contention", "cache invalidation"),
        "A modular service boundary keeps the interview architecture understandable, while a single core service can still be split later if independent scaling needs appear.",
        List.of(
            "What is the source of truth for %s?".formatted(systemName),
            "Which workflows must be synchronous?",
            "What data should be cached and for how long?",
            "How would you handle retries and duplicate jobs?"),
        List.of(
            "Generated from the prompt instead of a canned design.",
            "The core path stays simple: client, gateway, service, database.",
            "Background work is isolated through a queue so user requests stay responsive."));
  }

  private MockSystemDesign whatsappDesign() {
    return new MockSystemDesign(
        "WhatsApp Chat System",
        "A chat system needs low-latency message delivery, durable message storage, online presence, push notifications, and eventual delivery across devices.",
        List.of(
            node("mobile-client", "mobile", "Mobile Client", "Sends messages and receives realtime updates."),
            node("gateway", "gateway", "API Gateway", "Authenticates users and routes requests."),
            node("chat-service", "service", "Chat Service", "Validates messages and manages conversations."),
            node("presence-service", "service", "Presence Service", "Tracks online state and typing indicators."),
            node("message-queue", "queue", "Message Queue", "Buffers fanout and retry delivery."),
            node("websocket", "websocket", "Realtime Gateway", "Pushes live messages to connected devices."),
            node("message-db", "database", "Message Store", "Persists message history."),
            node("cache", "cache", "Session Cache", "Caches user sessions and device routing.")),
        List.of(
            edge("mobile-client", "gateway", "HTTPS"),
            edge("gateway", "chat-service", "send"),
            edge("gateway", "presence-service", "presence"),
            edge("chat-service", "message-db", "persist"),
            edge("chat-service", "message-queue", "fanout"),
            edge("message-queue", "websocket", "deliver"),
            edge("cache", "websocket", "route device")),
        List.of("One-to-one messaging", "group message fanout", "presence and typing indicators", "offline delivery"),
        List.of("Chat Service persists messages", "Queue handles fanout retries", "Realtime Gateway maintains device sockets", "Cache maps users to active sessions"),
        "Shard conversations by conversation id, separate presence from durable chat, and use queues for retryable delivery.",
        List.of("large group fanout", "offline delivery retries", "multi-device ordering", "presence churn"),
        "Strong ordering per conversation costs throughput; eventual delivery improves scale but complicates client reconciliation.",
        List.of("How do you preserve message ordering?", "How does group fanout work?", "How are offline users handled?", "Where does end-to-end encryption fit?"),
        List.of("Queues smooth fanout spikes.", "Presence is separated because it is hot and ephemeral.", "Message storage is the source of truth."));
  }

  private MockSystemDesign netflixDesign() {
    return new MockSystemDesign(
        "Netflix Streaming Architecture",
        "A streaming platform separates playback control, metadata, CDN delivery, personalization, and observability for a globally distributed viewing experience.",
        List.of(
            node("tv-mobile", "mobile", "Client Apps", "Browse and play content across devices."),
            node("cdn", "cdn", "CDN Edge", "Serves video segments close to viewers."),
            node("gateway", "gateway", "API Gateway", "Routes playback and catalog APIs."),
            node("catalog", "service", "Catalog Service", "Provides metadata and availability."),
            node("playback", "service", "Playback Service", "Issues manifests and entitlement checks."),
            node("recommendations", "service", "Recommendation Service", "Ranks personalized rows."),
            node("event-stream", "kafka", "Viewing Event Stream", "Captures playback telemetry."),
            node("metadata-db", "database", "Metadata DB", "Stores titles, assets, and availability."),
            node("cache", "cache", "Edge Cache", "Caches metadata and manifests.")),
        List.of(
            edge("tv-mobile", "cdn", "video segments"),
            edge("tv-mobile", "gateway", "API"),
            edge("gateway", "catalog", "browse"),
            edge("gateway", "playback", "manifest"),
            edge("catalog", "metadata-db", "metadata"),
            edge("playback", "cache", "manifest cache"),
            edge("tv-mobile", "event-stream", "telemetry"),
            edge("event-stream", "recommendations", "features")),
        List.of("browse catalog", "start playback", "stream video from CDN", "capture viewing events"),
        List.of("CDN delivers video", "Playback Service creates manifests", "Catalog Service serves metadata", "Recommendation Service ranks rows"),
        "Push video to CDN edges, cache manifests aggressively, and stream telemetry asynchronously.",
        List.of("CDN cache misses", "regional catalog consistency", "recommendation freshness", "startup latency"),
        "CDN-heavy delivery reduces origin load but requires careful cache invalidation and regional rights management.",
        List.of("Why separate CDN from API services?", "How do you reduce playback startup time?", "How are recommendations updated?", "What should happen during regional outage?"),
        List.of("CDN is the critical scaling primitive.", "Telemetry should not block playback.", "Metadata cache freshness is a product tradeoff."));
  }

  private MockSystemDesign youtubeDesign() {
    return new MockSystemDesign(
        "YouTube Recommendation System",
        "A recommendation system combines candidate generation, ranking, feature storage, event streams, and online serving with low-latency personalization.",
        List.of(
            node("web-client", "mobile", "Web/Mobile Client", "Requests home feed and emits engagement events."),
            node("gateway", "gateway", "API Gateway", "Routes feed and engagement APIs."),
            node("feed-service", "service", "Feed Service", "Builds personalized feeds."),
            node("candidate-service", "service", "Candidate Generator", "Fetches potential videos."),
            node("ranking-service", "service", "Ranking Service", "Scores candidates in realtime."),
            node("feature-store", "database", "Feature Store", "Serves user/video features."),
            node("event-stream", "kafka", "Engagement Stream", "Collects watches, likes, skips, and impressions."),
            node("cache", "cache", "Feed Cache", "Caches short-lived feed pages.")),
        List.of(
            edge("web-client", "gateway", "feed request"),
            edge("gateway", "feed-service", "GET /feed"),
            edge("feed-service", "candidate-service", "candidates"),
            edge("feed-service", "ranking-service", "rank"),
            edge("ranking-service", "feature-store", "features"),
            edge("feed-service", "cache", "cache feed"),
            edge("web-client", "event-stream", "events"),
            edge("event-stream", "feature-store", "update features")),
        List.of("generate personalized home feed", "log engagement events", "refresh features", "rank candidates"),
        List.of("Candidate Generator narrows search space", "Ranking Service scores items", "Feature Store serves low-latency features", "Kafka captures engagement"),
        "Cache feed pages briefly, precompute candidates offline, and keep online ranking latency bounded.",
        List.of("ranking latency", "feedback loops", "feature freshness", "cold starts"),
        "More personalization improves relevance but increases latency and operational complexity.",
        List.of("How do candidate generation and ranking differ?", "How do you handle cold-start users?", "How fresh should features be?", "How do you avoid filter bubbles?"),
        List.of("Candidate generation protects ranking from huge search spaces.", "Feature freshness affects relevance.", "Event streams power retraining and online updates."));
  }

  private Map<String, Object> node(String id, String type, String label, String description) {
    return Map.of(
        "id", id,
        "type", type,
        "data", Map.of("label", label, "description", description));
  }

  private Map<String, Object> edge(String source, String target, String label) {
    return Map.of("source", source, "target", target, "label", label);
  }

  private record MockSystemDesign(
      String title,
      String overview,
      List<Map<String, Object>> nodes,
      List<Map<String, Object>> edges,
      List<String> functionalRequirements,
      List<String> components,
      String scaling,
      List<String> bottlenecks,
      String tradeoffs,
      List<String> interviewQuestions,
      List<String> explanation) {}
}
