import type { ArchitectureNodeType } from "../types/diagram";

export type ArchitectureComponent = {
  id: string;
  label: string;
  nodeType: ArchitectureNodeType;
  description: string;
  group:
    | "Compute"
    | "Storage"
    | "Database"
    | "Networking"
    | "Messaging"
    | "Security"
    | "Analytics"
    | "Monitoring"
    | "Containers"
    | "DevOps"
    | "Frontend"
    | "Backend"
    | "AI"
    | "Generic";
  badge?: string;
  provider?: string;
};

export const architectureComponents: ArchitectureComponent[] = [
  {
    id: "aws-cloud",
    label: "AWS Cloud",
    nodeType: "aws",
    description: "Boundary for AWS-hosted infrastructure.",
    group: "Generic",
    badge: "AWS",
    provider: "AWS",
  },
  {
    id: "ec2",
    label: "EC2",
    nodeType: "ec2",
    description: "Virtual compute instances for services and workloads.",
    group: "Compute",
    badge: "AWS",
    provider: "AWS",
  },
  {
    id: "lambda",
    label: "Lambda",
    nodeType: "lambda",
    description: "Serverless functions for event-driven workloads.",
    group: "Compute",
    badge: "AWS",
    provider: "AWS",
  },
  {
    id: "ecs",
    label: "ECS",
    nodeType: "ecs",
    description: "Container orchestration for service workloads.",
    group: "Compute",
    badge: "AWS",
    provider: "AWS",
  },
  {
    id: "eks",
    label: "EKS",
    nodeType: "eks",
    description: "Managed Kubernetes for container platforms.",
    group: "Compute",
    badge: "AWS",
    provider: "AWS",
  },
  {
    id: "alb",
    label: "Load Balancer",
    nodeType: "loadBalancer",
    description: "Distributes traffic across healthy backend targets.",
    group: "Networking",
    badge: "ALB",
    provider: "AWS",
  },
  {
    id: "api-gateway",
    label: "API Gateway",
    nodeType: "apiGateway",
    description: "Managed API ingress, auth, throttling, and routing.",
    group: "Networking",
    badge: "AWS",
    provider: "AWS",
  },
  {
    id: "cloudfront",
    label: "CloudFront",
    nodeType: "cloudfront",
    description: "CDN edge delivery for static assets and cached responses.",
    group: "Networking",
    badge: "AWS",
    provider: "AWS",
  },
  {
    id: "vpc",
    label: "VPC",
    nodeType: "vpc",
    description: "Network boundary for private subnets and routing.",
    group: "Networking",
    badge: "AWS",
    provider: "AWS",
  },
  {
    id: "s3",
    label: "S3",
    nodeType: "s3",
    description: "Object storage for files, exports, media, and artifacts.",
    group: "Storage",
    badge: "AWS",
    provider: "AWS",
  },
  {
    id: "rds",
    label: "RDS",
    nodeType: "rds",
    description: "Managed relational database for transactional data.",
    group: "Database",
    badge: "AWS",
    provider: "AWS",
  },
  {
    id: "dynamodb",
    label: "DynamoDB",
    nodeType: "dynamodb",
    description: "Managed key-value and document database.",
    group: "Database",
    badge: "AWS",
    provider: "AWS",
  },
  {
    id: "elasticache",
    label: "ElastiCache",
    nodeType: "redis",
    description: "Managed Redis cache for hot reads and sessions.",
    group: "Database",
    badge: "AWS",
    provider: "AWS",
  },
  {
    id: "opensearch",
    label: "OpenSearch",
    nodeType: "opensearch",
    description: "Search and analytics index for text and logs.",
    group: "Analytics",
    badge: "AWS",
    provider: "AWS",
  },
  {
    id: "sqs",
    label: "SQS",
    nodeType: "sqs",
    description: "Managed queue for async work and retries.",
    group: "Messaging",
    badge: "AWS",
    provider: "AWS",
  },
  {
    id: "sns",
    label: "SNS",
    nodeType: "sns",
    description: "Pub/sub notification fanout.",
    group: "Messaging",
    badge: "AWS",
    provider: "AWS",
  },
  {
    id: "azure-functions",
    label: "Azure Functions",
    nodeType: "lambda",
    description: "Azure serverless functions for event workloads.",
    group: "Compute",
    badge: "Azure",
    provider: "Azure",
  },
  {
    id: "azure-service-bus",
    label: "Service Bus",
    nodeType: "queue",
    description: "Azure broker for queues and pub/sub topics.",
    group: "Messaging",
    badge: "Azure",
    provider: "Azure",
  },
  {
    id: "azure-cosmos-db",
    label: "Cosmos DB",
    nodeType: "dynamodb",
    description: "Globally distributed NoSQL database.",
    group: "Database",
    badge: "Azure",
    provider: "Azure",
  },
  {
    id: "gcp-cloud-storage",
    label: "Cloud Storage",
    nodeType: "s3",
    description: "GCP object storage for blobs and artifacts.",
    group: "Storage",
    badge: "GCP",
    provider: "Google Cloud",
  },
  {
    id: "gcp-pubsub",
    label: "Pub/Sub",
    nodeType: "queue",
    description: "Google Cloud event streaming and messaging.",
    group: "Messaging",
    badge: "GCP",
    provider: "Google Cloud",
  },
  {
    id: "bigquery",
    label: "BigQuery",
    nodeType: "database",
    description: "Serverless analytics warehouse.",
    group: "Analytics",
    badge: "GCP",
    provider: "Google Cloud",
  },
  {
    id: "docker",
    label: "Docker",
    nodeType: "ecs",
    description: "Containerized runtime or image build boundary.",
    group: "Containers",
    badge: "Docker",
    provider: "Docker",
  },
  {
    id: "kubernetes",
    label: "Kubernetes",
    nodeType: "eks",
    description: "Container orchestration cluster.",
    group: "Containers",
    badge: "K8s",
    provider: "Kubernetes",
  },
  {
    id: "nginx",
    label: "NGINX",
    nodeType: "gateway",
    description: "Reverse proxy, gateway, or ingress controller.",
    group: "Networking",
    badge: "NGINX",
    provider: "NGINX",
  },
  {
    id: "cloudflare",
    label: "Cloudflare",
    nodeType: "cdn",
    description: "Edge proxy, CDN, DNS, and perimeter controls.",
    group: "Networking",
    badge: "CF",
    provider: "Cloudflare",
  },
  {
    id: "redis",
    label: "Redis",
    nodeType: "redis",
    description: "In-memory cache, rate limiter, or queue backend.",
    group: "Database",
    badge: "Redis",
    provider: "Redis",
  },
  {
    id: "postgresql",
    label: "PostgreSQL",
    nodeType: "database",
    description: "Relational database for transactional data.",
    group: "Database",
    badge: "PG",
    provider: "PostgreSQL",
  },
  {
    id: "mysql",
    label: "MySQL",
    nodeType: "database",
    description: "Relational database for product data.",
    group: "Database",
    badge: "SQL",
    provider: "MySQL",
  },
  {
    id: "mongodb",
    label: "MongoDB",
    nodeType: "dynamodb",
    description: "Document database for flexible records.",
    group: "Database",
    badge: "Mongo",
    provider: "MongoDB",
  },
  {
    id: "cassandra",
    label: "Cassandra",
    nodeType: "database",
    description: "Wide-column database for high write volume.",
    group: "Database",
    badge: "C*",
    provider: "Cassandra",
  },
  {
    id: "kafka",
    label: "Kafka",
    nodeType: "kafka",
    description: "Distributed event log for streaming systems.",
    group: "Messaging",
    badge: "Kafka",
    provider: "Apache Kafka",
  },
  {
    id: "rabbitmq",
    label: "RabbitMQ",
    nodeType: "queue",
    description: "Message broker for routing and async work.",
    group: "Messaging",
    badge: "RMQ",
    provider: "RabbitMQ",
  },
  {
    id: "prometheus",
    label: "Prometheus",
    nodeType: "opensearch",
    description: "Metrics collection and alerting.",
    group: "Monitoring",
    badge: "Prom",
    provider: "Prometheus",
  },
  {
    id: "grafana",
    label: "Grafana",
    nodeType: "service",
    description: "Dashboards for metrics, traces, and logs.",
    group: "Monitoring",
    badge: "Graf",
    provider: "Grafana",
  },
  {
    id: "github",
    label: "GitHub",
    nodeType: "service",
    description: "Source control and collaboration.",
    group: "DevOps",
    badge: "GH",
    provider: "GitHub",
  },
  {
    id: "github-actions",
    label: "GitHub Actions",
    nodeType: "queue",
    description: "CI/CD automation workflows.",
    group: "DevOps",
    badge: "CI",
    provider: "GitHub",
  },
  {
    id: "jenkins",
    label: "Jenkins",
    nodeType: "service",
    description: "Build, test, and deployment automation.",
    group: "DevOps",
    badge: "CI",
    provider: "Jenkins",
  },
  {
    id: "terraform",
    label: "Terraform",
    nodeType: "service",
    description: "Infrastructure as code provisioning.",
    group: "DevOps",
    badge: "IaC",
    provider: "HashiCorp",
  },
  {
    id: "flink",
    label: "Apache Flink",
    nodeType: "kafka",
    description: "Stateful stream processing jobs.",
    group: "Analytics",
    badge: "Flink",
    provider: "Apache Flink",
  },
  {
    id: "spark",
    label: "Spark",
    nodeType: "service",
    description: "Batch and distributed analytics compute.",
    group: "Analytics",
    badge: "Spark",
    provider: "Apache Spark",
  },
  {
    id: "airflow",
    label: "Airflow",
    nodeType: "queue",
    description: "Workflow orchestration for data pipelines.",
    group: "Analytics",
    badge: "DAG",
    provider: "Apache Airflow",
  },
  {
    id: "clickhouse",
    label: "ClickHouse",
    nodeType: "database",
    description: "Fast columnar analytics database.",
    group: "Analytics",
    badge: "CH",
    provider: "ClickHouse",
  },
  {
    id: "snowflake",
    label: "Snowflake",
    nodeType: "database",
    description: "Cloud data warehouse.",
    group: "Analytics",
    badge: "Snow",
    provider: "Snowflake",
  },
  {
    id: "web-client",
    label: "Web Client",
    nodeType: "mobile",
    description: "Browser application entry point.",
    group: "Frontend",
    badge: "Web",
  },
  {
    id: "mobile-app",
    label: "Mobile App",
    nodeType: "mobile",
    description: "iOS or Android application.",
    group: "Frontend",
    badge: "App",
  },
  {
    id: "backend-service",
    label: "Backend Service",
    nodeType: "service",
    description: "API or worker service that owns domain logic.",
    group: "Backend",
    badge: "API",
  },
  {
    id: "auth-service",
    label: "Auth Service",
    nodeType: "gateway",
    description: "Authentication and authorization boundary.",
    group: "Security",
    badge: "Auth",
  },
  {
    id: "ml-service",
    label: "ML Service",
    nodeType: "service",
    description: "Model inference, ranking, or AI workflow service.",
    group: "AI",
    badge: "AI",
  },
  {
    id: "vector-db",
    label: "Vector DB",
    nodeType: "database",
    description: "Embedding storage for semantic search and RAG.",
    group: "AI",
    badge: "Vec",
  },
  {
    id: "service",
    label: "Service",
    nodeType: "service",
    description: "Application service that owns business logic.",
    group: "Generic",
  },
  {
    id: "client",
    label: "Client",
    nodeType: "mobile",
    description: "Web, mobile, or device client.",
    group: "Generic",
  },
  {
    id: "database",
    label: "Database",
    nodeType: "database",
    description: "Durable source-of-truth datastore.",
    group: "Generic",
  },
];

export const architectureComponentGroups = [
  "Compute",
  "Storage",
  "Database",
  "Networking",
  "Messaging",
  "Security",
  "Analytics",
  "Monitoring",
  "Containers",
  "DevOps",
  "Frontend",
  "Backend",
  "AI",
  "Generic",
] as const;
